<?php
if($block->isEnable() > 0)
{
$quote = $block->getQuote();
$items = $block->getItems();
$is_multiple_cart = $block->getMultipleCart();

?>

<div id="modal-content" style="display: none">
    <h4><?= $block->getContent(); count($items); ?></h4>
    <br/><br/>
    <?php foreach ($items as $item)
    {
        echo ($item->getName());
        echo("<br/><br/>");
    }
    ?>

</div>
<?php
if($is_multiple_cart > 0)
{
?>
<script type="text/x-magento-init">

        {
            ".tocart" : {
                "AddToCart-modal" : "<?= $block->getBaseUrl() ?>"
            }
        }

</script>
<?php } }?>